### ISSUE TITLE
Add structured logging panic handlers to all launched go routines

### ISSUE THREAD

**Issue by amckague** [atlassian/ctrl#23]
Directly I can see leader election, startstoptlsserver, and canceloninterrupt directly launching go routines. If they panic we end up with golangs default multi-line panic printer. Each of these cases (and any other I missed) should allow calling code to set a panic handling function to be called in the event of a panic in their launched go routine. 

Code would accept a no arg func() and defer it.

A default implementation of that such a panic handler might look like this:

```
func StructuredRecover() {
	if r := recover(); r != nil {
		structuredPanic(os.Stderr, r, time.Now().Format(time.RFC3339), debug.Stack())
		panic(r)
	}
}

func structuredPanic(out io.Writer, i interface{}, time string, stack []byte) {
	bytes, err := json.Marshal(struct {
		Level   string `json:"level"`
		Time    string `json:"time"`
		Message string `json:"msg"`
		Stack   string `json:"stack"`
	}{
		Level:   "fatal",
		Time:    time,
		Message: fmt.Sprintf("%v", i),
		Stack:   string(stack),
	})
	if err != nil {
		fmt.Fprintf(out, "error while serializing cmd exit panic: %+v\n", err) // nolint: errcheck
		fmt.Fprintf(out, "original panic: %+v\n", i)                           // nolint: errcheck
		return
	}
	fmt.Fprintf(out, "%s\n", bytes) // nolint: errcheck
}
```

@ash2k thoughts?

**Comment by amckague** [comment]
This would also involve threading such handlers into github.com/ash2k/wait/group.go or bringing that code into ctrl and modifying it.

**Comment by ash2k** [comment]
I don't think complicating code is worth the result. Also, what about all the 3rd party code that spawns goroutines that we cannot modify?

Also see https://github.com/golang/go/issues/16340

**Comment by amckague** [comment]
A response in two parts. To your question about third party libraries:

Ctrl is a good of a library that does not allow it's go routines to be "participated" in. That's why I'm proposing a mechanism to add such a mechanism in. Most web server libraries have this behaviour baked into their core code https://github.com/go-chi/chi/blob/master/middleware/recoverer.go. There you can see an easy way to add a recover logger to all http request. (we'd probably write our own). It's not a singular decision whether or not it's a good idea to log panics it's an ongoing discussion about how hard it is to add the behaviour in. (we can always try to upstream changes). 

I'm not particularly excited with the alternative ideas around wrapping turning all our docker images into wrapper script that does log parsing/redirection and runs a sub process that happens to be a go binary  or trying to get fluentd to do conditional mutliline log parsing. If you can think of another alternative please suggest it.


To your referenced issue:
Dynamically hooking into the runtime and running arbitrary code falls over under it's own weight regardless of the problem it's attempting to solve.

Moving instead to the process of standardizing our own log printing there are at least two problems with the idealized version of reality being held up as the reason to stop that original feature that don't apply to our internal code. The first is a mismatches in quantity of occurrences and the second is a good example of disallowing some good because you can't fix all the bad cases.

In practice our pile of code crashes regularly. In most cases the crash is caused by mishandling a nil. Each individual failure is fixable given enough knowledge about how to dig into the system and debug the problem. In aggregate each of those fixes run up against the mismatch between our single line json oriented logging infrastructure and the mutliline dump golang's default panic handling prints. Multiline data is difficult to work with in Splunk where we want to be doing broad analysis of failures rather than localized fixes of the current crash looping panic. 

Another idea nested inside the the linked issue brings up concerns over attempting to execute code during an out of memory panic. This is a fine point against the dynamically inject arbitrary code into the runtime. It's not a good point when looking at the subset of panics we commonly deal with. If we touch a nil when we didn't mean to we will have enough memory to print out a well structured log message. Not all panics are unrecordable.

We also don't write crash only software. We rely on service catalog which panics during event processing, prints to stderr, and goes right on running. We run various cmds that use the http package to run buggy code in request handlers that generally don't take down the entire app when they panic. These kinds of failures need to be easily identifiable to and in our logging tools. Those tool work best with single line stack traces associated directly to a single failure message.

So in general the linked issue misses the point I'm trying to address here. I want as many cases where we commonly panic as possible to have a standardised single line json output.

**Comment by ash2k** [comment]
Sounds reasonable. I'd make the handler optional - i.e. if it is set then and only then call `recover()`. And then it it returns a value, pass it to the handler. And then re-panic.
Re. `github.com/ash2k/stager` - why not just wrap the passed function and catch panics in the wrapper?

**Comment by amckague** [comment]
Wrapping the functions inside ctrl before passing them to stager is the right direction to go.
